name: Build and Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version-file: global.json
          cache: true

      - name: Build .NET projects
        shell: pwsh
        run: ./scripts/01-build.ps1 -NoImage

      - name: Build NodeManager Docker image
        run: docker compose -f docker/docker-compose.yml build nodemanager